### ISSUE TITLE
[Apotheosis][Raytraced Black Holes] Giant Toxic Worm Black Screen

### ISSUE THREAD

**Issue by khonkhortisan** [alex-3141/raytraced_black_holes#3]
The screen turns black when near the Giant Toxic Worm (which spawns on the right side of Coal Pits) ¿but only during the homing green ball attack? I assume that attack has a weak gravitational pull applied over a large area that's registering as a black hole, that's rendering larger than screen size. It's still possible to kill by teleporting away, then shooting in its general direction when its health bar reappears, but it's safer to just not spawn it at all.
![image](https://github.com/user-attachments/assets/f836459f-b751-47d2-812e-df0ab8278d72)

**Comment by Conga0** [comment]
This should now be fixed on Apotheosis's side, thankyou.
