### ISSUE TITLE
Graphic Location vs actual location in ultrawide mode

### ISSUE THREAD

**Issue by Festive4020** [alex-3141/raytraced_black_holes#4]
Several people have reported that the graphic is not located in the correct location relative to the black hole itself in games where people are playing with the noita ultrawide mod.

Here is an example one of them shared!

https://steamcommunity.com/sharedfiles/filedetails/?id=3344850214

**Comment by alex-3141** [comment]
Thanks for letting me know, this is now fixed in v1.0.3 👍
